### ISSUE TITLE
Problem installing on ubuntu 22.04

### ISSUE THREAD

**Issue by ghasemi931** [mobile-insight/mobileinsight-core#119]
I get the following error when installing on ubuntu 22.04:

** Installer Script for mobileinsight-core on Ubuntu **
 
  Author : Zengwen Yuan (zyuan [at] cs.ucla.edu), Haotian Deng (deng164 [at] purdue.edu), Yuanjie Li (yuanjiel [at] tsinghua.edu.cn)
  Date   : 2020-10-20
  Rev    : 4.0
  Usage  : ./install-ubuntu.sh
 
Upgrading MobileInsight...
./uninstall.sh: line 12: python: command not found
Uninstalling MobileInsight-core v2.0 from your computer
This script will require sudo access to delete following files:
/home/mohsen/Programs/mobileinsight-core-master/MobileInsight.egg-info
/home/mohsen/Programs/mobileinsight-core-master/build
/home/mohsen/Programs/mobileinsight-core-master/dist
/home/mohsen/Programs/mobileinsight-core-master/ws_dissector/ws_dissector
/home/mohsen/Programs/mobileinsight-core-master/wireshark-2.0.*
/home/mohsen/.cache/Python-Eggs/MobileInsight*
/home/mohsen/.python-eggs/MobileInsight*
/usr/local/bin/mi-gui
/usr/local/bin/ws_dissector
/usr/local/share/mobileinsight/*
/usr/lib/libwireshark.so*
/usr/lib/libwsutil.so*
/usr/lib/libwireshark.6.dylib
/usr/lib/libwireshark.dylib
/usr/lib/libwiretap.5.dylib
/usr/lib/libwiretap.dylib
/usr/lib/libwsutil.6.dylib
/usr/lib/libwsutil.dylib

 
 
Uninstalling old MobileInsight build files and libs...
Uninstallation finished.
 
Installing dependencies for compiling Wireshark libraries
[sudo] password for mohsen: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libgcrypt20-dev' instead of 'libgcrypt-dev'
Package qt5-default is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'qt5-default' has no installation candidate
Checking Wireshark sources to compile ws_dissector
Configuring Wireshark sources for ws_dissector compilation...
Error when executing '/home/mohsen/Programs/mobileinsight-core-master/wireshark-3.4.0/cmake --disable-wireshark .'
You need to manually fix it before continuation. Exiting with status 3

**Comment by gamefreakoneone** [comment]
Hello, I am facing the exact same issue. How did you manage to resolve this?

**Comment by ghasemi931** [comment]
Hello, refer to this page to solve this problem.
https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04
