### ISSUE TITLE
Question for NB-IoT data collection and analytics

### ISSUE THREAD

**Issue by haroldfeng** [mobile-insight/mobileinsight-core#130]
I was recently researching NB-IoT communication signaling and found that MobileInsight supports this function, but after setting up a test environment, I found that the signaling could not be obtained.

In Windos environment, AT command was executed through COM port and Tashi device software to obtain IMEI and other information. However, in the Ubuntu environment, mobileinsight executes normally and cannot obtain signaling data. Therefore, I would like to ask about the models of NB-IoT devices supported by mobileinsight.

![D499E089-6DAF-4C54-BEF6-9B462D4C2769](https://github.com/mobile-insight/mobileinsight-core/assets/39725006/baf23b77-3779-420c-9f8f-313350cb08bd)
![DF56DC6E-1D17-446D-87F1-C3703ECFF21D](https://github.com/mobile-insight/mobileinsight-core/assets/39725006/305a30f9-ddf0-4fc4-bd50-365c8420e4cc)

**Comment by Aghiles1998** [comment]
The same probleme with me 
![Capture d’écran de 2024-01-14 11-01-10](https://github.com/mobile-insight/mobileinsight-core/assets/49618981/b56a26d9-5844-4b5f-aba1-9eb1df6f6374)

**Comment by haroldfeng** [comment]
@Aghiles1998 Your error message is about /dev/ttyUSB0 because the device diagnostics port was not recognized. The possible cause is that the corresponding driver is not installed or the device diagnostic mode is not enabled.

**Comment by Aghiles1998** [comment]
which option to choose here?
![Screenshot_20240114-132306](https://github.com/mobile-insight/mobileinsight-core/assets/49618981/5d5c4ffe-350d-4843-b2f4-aca7a30fd7ac)

**Comment by Aghiles1998** [comment]
how to verify this ?
Your error message is about /dev/ttyUSB0 because the device diagnostics port was not recognized. The possible cause is that the corresponding driver is not installed or the device diagnostic mode is not enabled.

**Comment by haroldfeng** [comment]
It doesn't seem to open from this option. My device is NB-IoT, which is not the same as UE.

Your command line result reads :"No such file or directory: '/dev/ttyUSB0' ". You can check to see if the file exists in /dev/.

**Comment by Aghiles1998** [comment]
yes for me is : tty0
![Capture d’écran de 2024-01-14 13-54-54](https://github.com/mobile-insight/mobileinsight-core/assets/49618981/26881b94-bea8-4d3c-a61b-411d48acb25a)

**Comment by Aghiles1998** [comment]
i plugged the google pixel 5 with my computer i try to collect data with the mobile application inisght 6 it doesn't work

**Comment by Aghiles1998** [comment]
I want a solution please ? 
![erreur](https://github.com/mobile-insight/mobileinsight-core/assets/49618981/0823d20a-c915-4fcd-8913-c01ef6ae4845)

**Comment by haroldfeng** [comment]
My device is now not satisfied with successful operation. Your error message is no device, should be needed to load usbserial. For example, `modprobe usbserial vendor=0x04e8 product=0x681c`.

Official tutorial reference: http://www.mobileinsight.net/get_started_desktop.html
