### ISSUE TITLE
Request for Step-by-Step Setup Tutorial for Beginners.

### ISSUE THREAD

**Issue by LevyTheDevy** [mobile-insight/mobileinsight-core#136]
## Description
I am new to MobileInsight and am finding the setup process to be quite complex. I believe a step-by-step tutorial would be incredibly helpful for beginners like myself.

## Why is this needed?
A detailed tutorial would make MobileInsight more accessible to a wider audience, especially those who are not as familiar with mobile network monitoring and analysis tools.

## Suggested Content for the Tutorial
- Pre-requisites and dependencies installation
- Cloning the MobileInsight repository
- Running the installation scripts for different operating systems
- Verifying the installation
- A simple example to get started

## Additional Context
I am particularly interested in [specific aspect, e.g., using MobileInsight for real-time network monitoring on Mac OSX]. Any advice or pointers in this area would also be greatly appreciated.

Thank you for considering my request.

**Comment by ixenion** [comment]
So...
Is there any tutorial?

**Comment by ixenion** [comment]
Because Im getting some stupid errors while ./install-ubuntu.sh which I obviously shouldnt.
Othervise what's the point of that shity script...
