### ISSUE TITLE
Mac osx mi-gui:ImportError  No module named animate

### ISSUE THREAD

**Issue by cn0xroot** [mobile-insight/mobileinsight-core#19]
Hi， nice project ,but some trouble when i use MobileInsight GUI:

### Versions

* OS:osx 10.12.6
* Python version:2.7.14
* Python installation method:with mac port
* 

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs

```
mobileinsight-core-3.0/gui   ./mi-gui
Traceback (most recent call last):
  File "/usr/local/share/mobileinsight/mobile_insight_gui.py", line 12, in <module>
    import wx.animate
ImportError: No module named animate
```
can you tell me how to fix?thanks!

**Comment by zwyuan** [comment]
Thanks for the feedback. It looks like the misconfig of python path to me.
Can you check your `PYTHON_PATH`? The `mobile_insight_gui.py` uses `#!/usr/bin/python`
Or you may delete this shebang and see if it works.

**Comment by cn0xroot** [comment]
```
which python
/usr/local/opt/python/libexec/bin/python
```
I has try `/usr/bin/python mobile_insight_gui.py` and delete `#!/usr/bin/python`
but has the same result：

```
Traceback (most recent call last):
  File "/usr/local/share/mobileinsight/mobile_insight_gui.py", line 12, in <module>
    import wx.animate
```

**Comment by zwyuan** [comment]
Yeah, that won't work because you said your python is installed via MacPorts and is at `/usr/local/opt/python/libexec/bin/python`. The MobileInsight GUI installs the `wxPython` using Homebrew, which may not be found by the Python you specified.

So if you are using Python installed via MacPorts, can you also install `wxPython` via MacPorts or make sure the Python can find it?

**Comment by cn0xroot** [comment]
```
hacksmith@parrot]─[~]
└──╼ $whereis python
python: /usr/bin/python /usr/bin/python2.7-config /usr/bin/python3.6m /usr/bin/python3.5m /usr/bin/python3.6 /usr/bin/python2.7 /usr/bin/python3.5 /usr/lib/python3.6 /usr/lib/python2.7 /usr/lib/python3.5 /usr/lib/python2.6 /etc/python /etc/python3.6 /etc/python2.7 /etc/python3.5 /usr/local/lib/python3.6 /usr/local/lib/python2.7 /usr/local/lib/python3.5 /usr/include/python3.6m /usr/include/python3.5m /usr/include/python2.7 /usr/share/python /usr/share/man/man1/python.1.gz
```
```

~/mobileinsight-core/gui]
└──╼ $python mobile_insight_gui.py 
Traceback (most recent call last):
  File "mobile_insight_gui.py", line 436, in <module>
    main()
  File "mobile_insight_gui.py", line 432, in main
    app.frame = WindowClass(None)
  File "mobile_insight_gui.py", line 166, in __init__
    self.basicGUI()
  File "mobile_insight_gui.py", line 170, in basicGUI
    self._log_analyzer = LogAnalyzer(self.OnReadComplete)
  File "build/bdist.linux-x86_64/egg/mobile_insight/analyzer/log_analyzer.py", line 34, in __init__
  File "build/bdist.linux-x86_64/egg/mobile_insight/monitor/offline_replayer.py", line 68, in __init__
  File "build/bdist.linux-x86_64/egg/mobile_insight/monitor/dm_collector/dm_endec/dm_log_packet.py", line 407, in init
  File "build/bdist.linux-x86_64/egg/mobile_insight/monitor/dm_collector/dm_endec/ws_dissector.py", line 103, in init_proc
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by zwyuan** [comment]
Thanks for reporting detailed log.

1. Unfortunately, we can only support Homebrew installation on macOS due to limited resources.
The essential steps this script does are:

+ Download, compile and install Wireshark-2.0.13 shared libs
+ Compile and install Wireshark dissector (`ws_dissector`) using downloaded Wireshark-2.0.13 sources

```
echo "Compiling Wireshark dissector for MobileInsight..."
cd ${MOBILEINSIGHT_PATH}/ws_dissector
if [ -e "ws_dissector" ]; then
    rm ws_dissector
fi
g++ ws_dissector.cpp packet-aww.cpp -o ws_dissector `pkg-config --libs --cflags glib-2.0` \
    -I"${WIRESHARK_SRC_PATH}" -L"${LD_LIBRARY_PATH}" -lwireshark -lwsutil -lwiretap
strip ws_dissector
```

+ Install `wxPython` for MobileInsight GUI
+ Perform `python setup.py install` for the MobileInsight-core package.

You should be able to adapt the macOS installation script to support MacPorts following the above steps as well.

2. For Linux installation, we tested on the Ubuntu 14.04/16.04 and it worked fine.
@moonsky219 should be able to take a look into your specific problem.

3. For more deployment environment details, you can refer to our all-in-one VM: https://github.com/mobile-insight/mobileinsight-dev

**Comment by cn0xroot** [comment]
Thanks for quickly reply.

I'll try to use it with Vagrant and VirtualBox.

**Comment by hazelnutsgz** [comment]
@cn0xroot  Have you ever checked your wxpython version in your python command line by wx.__version__? since the module `wx.animate` move to `wx.avd` in version 4* [click here](https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html#modules-which-have-moved).

**Comment by baesangwook89** [comment]
Here is my ad-hoc solution.
Modify the mobileinsight-core/gui/mobile_insight_gui.py as followings.

First of all, as @hazelnutsgz already mentioned above, wxPython is updated and the wx.animate is deprecated one. Therefore, you need to change the code as followings.
In line 12, `import wx.animate` -->`import wx.adv`

Second, even if I changed the code, still I got an error.  The main reason for the error is the same as before (wx.animate). So, I removed the code line related to wx.animated. Here is a quick but dirty solution. 

_Remove/comment from line 56 to 61._ 
Followings are the code that I removed.
```
        gif = wx.animate.GIFAnimationCtrl(
            self, -1, "icons/progress.gif", pos=(0, 0), size=(-1, -1))
        gif.GetPlayer().UseBackgroundColour(True)
        gif.Play()

        mainSizer.Add(gif, wx.EXPAND | wx.ALL)
```
Hope that my solution be helpful for you.
Sangwook

**Comment by vikiQiu** [comment]
I tried the python 2.7.15 installed by brew, and then this problem disappears. You can try it.
Be attention, you should `brew link python@2`
