### ISSUE TITLE
Unable to identify qualacomm modem 

### ISSUE THREAD

**Issue by harpreet-s** [mobile-insight/mobileinsight-core#39]
Hi ,

The modem check is done through getprop - where qualacomm is identified through MSM or MDM.
With Qualacomm snapdragon 845 , value is 
[ro.board.platform]: [sdm845]

Therefore app is unable to work properly.

**Comment by zwyuan** [comment]
Thanks @harpreet-s  for reporting this issue.
Commit f2a5a4a has fixed it. We will update master branch soon as well.
