### ISSUE TITLE
Mac osx: No module named mobile_insight.analyzer

### ISSUE THREAD

**Issue by vikiQiu** [mobile-insight/mobileinsight-core#44]
### Versions

* OS: 10.12.6
* Python version: 2.7.14
* Python installation method: build-in
* 

### Description

When execute gui file by ·./mi-gui` after successfully installing MobileInsight-3.4.0 core, it shows `ImportError: No module named mobile_insight.analyzer`

### Code and Logs

```shell
cd MobileInsight-3.4.0
sh install-macos.sh # successfully installed while with lots of warnings
cd gui
./mi-gui
```
Errors shows after executing `./mi-gui`:
```
Traceback (most recent call last):
  File "/usr/local/share/mobileinsight/mobile_insight_gui.py", line 25, in <module>
    from mobile_insight.analyzer import LogAnalyzer
ImportError: No module named mobile_insight.analyzer
```
This error is similar to the warning shows in the installation process, which is `[WARNING] Failed to run offline analysis example!`.

Do I really install the MobileInsight correctly?
Although there exist many warnings, it shows that `Congratulations! mobileinsight-core is successfully installed!`. I'm so confused.

### Warnings while installing MobileInsight
- 'pow' is ambiguous problem:
```
In file included from dm_collector_c/export_manager.cpp:14:
dm_collector_c/log_packet_helper.h:191:39: error: call to 'pow' is ambiguous
        temp = (int)buffer[0] & ((int)std::pow(2, left_remaining) - 1);
                                      ^~~~~~~~
/usr/include/c++/4.2.1/cmath:365:3: note: candidate function
  pow(double __x, int __i)
  ^
/usr/include/c++/4.2.1/cmath:369:3: note: candidate function
  pow(float __x, int __n)
  ^
/usr/include/c++/4.2.1/cmath:373:3: note: candidate function
  pow(long double __x, int __n)
  ^
/usr/include/math.h:443:15: note: candidate function
extern double pow(double, double);
              ^
/usr/include/c++/4.2.1/cmath:357:3: note: candidate function
  pow(float __x, float __y)
  ^
/usr/include/c++/4.2.1/cmath:361:3: note: candidate function
  pow(long double __x, long double __y)
  ^
In file included from dm_collector_c/export_manager.cpp:14:
dm_collector_c/log_packet_helper.h:192:22: error: call to 'pow' is ambiguous
        rt += temp * std::pow(2, bitlength - left_remaining);
                     ^~~~~~~~
/usr/include/c++/4.2.1/cmath:365:3: note: candidate function
  pow(double __x, int __i)
  ^
/usr/include/c++/4.2.1/cmath:369:3: note: candidate function
  pow(float __x, int __n)
  ^
/usr/include/c++/4.2.1/cmath:373:3: note: candidate function
  pow(long double __x, int __n)
  ^
/usr/include/math.h:443:15: note: candidate function
extern double pow(double, double);
              ^
/usr/include/c++/4.2.1/cmath:357:3: note: candidate function
  pow(float __x, float __y)
  ^
/usr/include/c++/4.2.1/cmath:361:3: note: candidate function
  pow(long double __x, long double __y)
  ^
In file included from dm_collector_c/export_manager.cpp:14:
dm_collector_c/log_packet_helper.h:201:29: error: call to 'pow' is ambiguous
        temp = temp & ((int)std::pow(2, bitlength) - 1);
                            ^~~~~~~~
/usr/include/c++/4.2.1/cmath:365:3: note: candidate function
  pow(double __x, int __i)
  ^
/usr/include/c++/4.2.1/cmath:369:3: note: candidate function
  pow(float __x, int __n)
  ^
/usr/include/c++/4.2.1/cmath:373:3: note: candidate function
  pow(long double __x, int __n)
  ^
/usr/include/math.h:443:15: note: candidate function
extern double pow(double, double);
              ^
/usr/include/c++/4.2.1/cmath:357:3: note: candidate function
  pow(float __x, float __y)
  ^
/usr/include/c++/4.2.1/cmath:361:3: note: candidate function
  pow(long double __x, long double __y)
  ^
3 errors generated.
error: command '/usr/bin/clang' failed with exit status 1
```
- MobileInsight offline analysis example problem
```
Traceback (most recent call last):
  File "offline-analysis-example.py", line 11, in <module>
    from mobile_insight.monitor import OfflineReplayer
ImportError: No module named mobile_insight.monitor
```

**Comment by vikiQiu** [comment]
I find that there is no mobile_insight directory in `/usr/local/share/mobileinsight`
I tried to copy the mobile_insight into the directory, then it shows another problem:
```
File "/usr/local/share/mobileinsight/mobile_insight/monitor/dm_collector/dm_collector.py", line 22, in <module>
    import dm_collector_c
ImportError: No module named dm_collector_c
```

**Comment by yuanjieli** [comment]
It seems that the Python path is still not correctly linked via Brew on
yout MacOS. MobileInsight is thus not installed to the right direction.
Please double check your Python2 environment and ensure it is correctly
linked to the default path on Mac.

Sent from my phone. Apologies for the typos

vikiQiu <notifications@github.com> 于 2018年11月27日周二 上午7:42写道：

**Comment by yuanjieli** [comment]
It seems that the Python path is still not correctly linked via Brew on yout MacOS. MobileInsight is thus not installed to the right direction. Please double check your Python2 environment and ensure it is correctly linked to the default path on Mac

**Comment by vikiQiu** [comment]
> It seems that the Python path is still not correctly linked via Brew on yout MacOS. MobileInsight is thus not installed to the right direction. Please double check your Python2 environment and ensure it is correctly linked to the default path on Mac

I think I already fix the python path link problem by `brew link python@2`. It shows:
```
$ brew link python@2
Warning: Already linked: /usr/local/Cellar/python@2/2.7.15_1
To relink: brew unlink python@2 && brew link python@2
```
While the above problem still exists.

**Comment by yuanjieli** [comment]
What's the output of `which python`? Can you find `mobile_insight` package in `/Library/Python/2.7/site-packages/`?

**Comment by vikiQiu** [comment]
> What's the output of `which python`? Can you find `mobile_insight` package in `/Library/Python/2.7/site-packages/`?

I link the wrong python. The python version installed by brew is 2.7.15. Modify the ~/.bash_profile and add python 2.7.15 into the path. All problems are fixed. Thanks!

**Comment by rishieee** [comment]
I am facing the same issue, do we still need a python 2 enviroment or it should be python 3. As per the instruction it should be python3. Shall I link link it to python3 or python2? In this thread it was linked with python2

**Comment by JulianSchmidt96** [comment]
Why not try it with both Python versions and see which one works ?

I need to use python 3 for MI scripts
And python 2 for the GUI stuff

**Comment by rishieee** [comment]
> Why not try it with both Python versions and see which one works ?
> 
> I need to use python 3 for MI scripts And python 2 for the GUI stuff

Hello, Thank you for your response, I was able to make it running. There was some version issue of the Wireshark which I update and it worked. I wanted check if there is already a way to visualise the output of mobile insight, like RSRP etc.
