### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by vikiQiu** [mobile-insight/mobileinsight-core#45]
### Versions

* OS: 10.12.6
* Python version: 2.7.15
* Python installation method: brew
* Mobile Device: Google Nexus 6p with Android version 6.0

### Description

When I run the default NetLogger for a few minutes, it shows this problem on the screen

### Code and Logs
![_20181210103733](https://user-images.githubusercontent.com/15014997/49707740-a7b09a00-fc67-11e8-8151-2cefa6b5e18c.jpg)

**Comment by moonsky219** [comment]
A workaround would be skip run-time decoding in NetLogger.
