### ISSUE TITLE
GUI: Modem_debug_message

### ISSUE THREAD

**Issue by vikiQiu** [mobile-insight/mobileinsight-core#46]
### Versions

* OS: 10.12.6
* Python version: 2.7.15
* Python installation method: brew
* Mobile Device: Google Nexus 6p with Android version 6.0

### Description

When I visualize the logs collected from my android, it shows a modem debug message every 10 seconds. Is that a common phenomenon?

### Code and Logs
All the other messages time is correct, only the modem debug message's time is 1980-01-06.
```
<?xml version=« 1.0 » ?>
<dm_log_packet>
  <pair key=« type_id »>Modem_debug_message</pair>
  <pair key=« timestamp »>1980-01-06 00:00:00</pair>
  <pair key=« Version »>146</pair>
  <pair key=« Number of parameters »>4</pair>
  <pair key=« Timestamp »>1980-01-06 00:00:00</pair>
  <pair key=« Line of code »>4674</pair>
</dm_log_packet>
```

**Comment by moonsky219** [comment]
Yes, this is common, please just ignore the Modem_debug_message.
