### ISSUE TITLE
Parsing error on LTE_PHY_Serv_Cell_Measurement version 18.

### ISSUE THREAD

**Issue by Awaisryk** [mobile-insight/mobileinsight-core#51]
### Versions

* OS: Ubuntu
* Python version: 2.7.15

### Description

Please add support for LTE_PHY_Serv_Cell_Measurement version 18. I am facing the following error

### Logs
```
(MI)Unknown LTE PHY Subpacket version: 0x19 - 18
```
and following is the json it creates, with empty Subpackets array.
```python
{
  "log_msg_len": 112,
  "timestamp": "2019-03-08 18:08:00.021941",
  "type_id": "LTE_PHY_Serv_Cell_Measurement",
  "Subpackets": [], 
  "Version": 1, 
  "Number of SubPackets": 1
}

```
[Attached is the mi2log file.](https://github.com/mobile-insight/mobileinsight-core/files/2950593/665554-file.zip)

**Comment by ashish111189** [comment]
Having same problem. Could you please let me if you get the solution. @Awaisryk

**Comment by yuanjieli** [comment]
@Awaisryk @ashish111189 Thanks for your bug report. We have added the support  for LTE_PHY_Serv_Cell_Measurement version 18. Please pull the latest `dev` branch and let us know if there are any issues.

**Comment by ashish111189** [comment]
Hello Yuanjie,

I am having  the same issue 
[testlog.zip](https://github.com/mobile-insight/mobileinsight-core/files/3018786/testlog.zip)
with version 24.

Thanks,
Ashish
![Screenshot from 2019-03-28 11-26-09](https://user-images.githubusercontent.com/33262513/55170766-8065d600-514d-11e9-97b5-5d737914b4a5.png)

**Comment by moonsky219** [comment]
@ashish111189 Please check if you have installed the latest code in dev branch. After you pull the latest code, "sudo python setup.py install" should do the compile for dm_collector_module again.
