### ISSUE TITLE
Parsing error on LTE_PHY_Connected_mode_Neighbor_Measurement version 24

### ISSUE THREAD

**Issue by ashish111189** [mobile-insight/mobileinsight-core#54]
### Versions

* OS: Ubuntu
* Python version: 2.7.12 

### Description

Please add support for LTE_PHY_Connected_Mode_Neighbour_Measurement version 24. I am facing the following error

 Logs

(MI)Unknown LTE PHY Connected Neighbor Cell Meas subpkt id and version: 31 - 24

mi-gui output
?xml version="1.0" ?>
<dm_log_packet>
"log_msg_len" 180
LTE_PHY_Connected_Mode_Neighbor_Measurement
  "timestamp" 2019-03-29 14:39:02.255147
   "Version" 1 
   "Number of SubPackets" 2 
  "SubPackets" type = "list"
    
      
         "SubPacket ID" 30
          "Version" 3
         "SubPacket Size" 48
  
     
         "SubPacket ID" 31
         "Version" 24 
          "SubPacket Size" 116
    
[diag_log_20190329_103908_5662db1e88c26169678919616f6a59e3_motorola-motog(6)_310260.zip](https://github.com/mobile-insight/mobileinsight-core/files/3035247/diag_log_20190329_103908_5662db1e88c26169678919616f6a59e3_motorola-motog.6._310260.zip)

**Comment by moonsky219** [comment]
Hello @ashish111189, I just made an update in branch update-dm-collector to parse this sub-packet using the same code of version 4. Unfortunately this sub-packet (ID 31) version 24 is out of our availability and we don't have a ground-truth to confirm the parsing correctness. Please be aware of this issue.

**Comment by moonsky219** [comment]
@ashish111189 I confirmed the parsing correctness.
