### ISSUE TITLE
Parsing error on LTE_PHY_Serv_Cell_Measurement version 24

### ISSUE THREAD

**Issue by ashish111189** [mobile-insight/mobileinsight-core#55]
### Versions

* OS: Ubuntu
* Python version: 2.7.12

### Description

Please add support for LTE_PHY_Serv_Cell_Measurement version 24. I am facing the following error

 Logs
(MI)Unknown LTE PHY Subpacket version: 0x19 - 24

json created
LTE_PHY_Serv_Cell_Measurement
   timestamp:2019-03-29 14:39:01.921850
   Version 1
   Number of SubPackets: 1
   Subpackets: list

   
[diag_log_20190329_103908_5662db1e88c26169678919616f6a59e3_motorola-motog(6)_310260.zip](https://github.com/mobile-insight/mobileinsight-core/files/3035275/diag_log_20190329_103908_5662db1e88c26169678919616f6a59e3_motorola-motog.6._310260.zip)

**Comment by moonsky219** [comment]
@ashish111189 The message is supported in branch dm_collector_c
