### ISSUE TITLE
python3 urllib package or python2 urllib2 package

### ISSUE THREAD

**Issue by PanJason** [mobile-insight/mobileinsight-core#81]
### Versions

* OS: Ubuntu 18.04
* Python version:  python 2.7.17
* Python installation method: 
* 

### Description

When I tried to convert an offline mi2log file to xml, I met with an Import Error, which said no module named request. However urllib is a python3 package. 
![image](https://user-images.githubusercontent.com/18373884/92320700-f1edc780-f055-11ea-9451-943fec4a73aa.png)

Should I modify the code and still use python2? Because when I tried to use python3, I met with another traceback.
![image](https://user-images.githubusercontent.com/18373884/92320728-219ccf80-f056-11ea-8f36-07fcfc187a16.png)

### Code and Logs

```python
import os
import sys

from mobile_insight.monitor import OfflineReplayer
from mobile_insight.analyzer import LteRrcAnalyzer, WcdmaRrcAnalyzer
from mobile_insight.analyzer import MsgLogger

src = OfflineReplayer()
path = input("Please input the path of mi2log you want to convert: ")
src.set_input_path(path)

dumper = MsgLogger()
dumper.set_source(src)
dumper.set_decoding(MsgLogger.XML)

src.run()

```

**Comment by luckiday** [comment]
Hi Jason, 

I tested your code, and it works properly at my side (python3.7 and mobileinsight-core 5.0.0). The current mobileinsight-core requires python3. Could you check whether the installation has been processed well on your side? Additionally, the virtual environment(NOT Conda) is recommended for installing mobileinsight. 

Thanks,
Yunqi

**Comment by PanJason** [comment]
That's strange. I didn't meet with any installation error. Offline analysis examples passed successfully.

**Comment by PanJason** [comment]
Is there any file or folder called 'dm_collector_c' in 'dm_collector' folder?

**Comment by luckiday** [comment]
> Is there any file or folder called 'dm_collector_c' in 'dm_collector' folder?

`dm_collector_c` module is an extension build with C++. After installing mobileinsight, you will have `dm_collector_c.py` in the folder of your python libraries, e.g. `.../lib/python3.7/site-packages/MobileInsight-5.0.0-py3.7-macosx-10.15-x86_64.egg/mobile_insight/monitor/dm_collector/`.

**Comment by PanJason** [comment]
Thanks. I installed MobileInsight in wsl2 and found that I had to move the sharedobject file `dm_collector_c.cpython-36m-x86_64-linux-gnu.so` from `...\build\lib.linux-x86_64-3.6\mobile_insight\monitor\dm_collector` to `...\mobile_insight\monitor\dm_collector`. Then it worked.
