### ISSUE TITLE
Memory Leak while decoding mi2log files

### ISSUE THREAD

**Issue by ywk0bwl** [mobile-insight/mobileinsight-core#89]
Hello,

I collected a fairly big (few GB) mi2log file over several hours and would like to use the OfflineReplayer to decode this into a file (json format). Unfortunately, the RAM fills up fairly quickly (>16GB) and then my PC crashes.
Thus, I suspect there might be a memory leak in the code, since it seems like the memory used for decoding previous messages is not freed up again.

As a workaround for me it might also be good for me if I could split the mi2log file into several smaller files. Is this possible?

Thanks and kind regards!

**Comment by luckiday** [comment]
Hi! Thanks for your feedback.
Can you share more information about how you collect the big file? Specifically, are you using the PC or Andoird for collecting logs, and which monitor/netlogger are you using? If you can share more information about your use case, it's easier for us to give some solutions to this issue.

**Comment by ywk0bwl** [comment]
Hi,
Thanks for your answer. I am using a PC (debian + cellular 4G mPCIe modem) and collected via enable_log_all() without "live decoding", so there are many messages. My plan was to do the analysis afterwards, but even decoding single types of messages fills up the RAM.

**Comment by dboyan** [comment]
Please try commenting out line 99 of [msg_logger.py](https://github.com/mobile-insight/mobileinsight-core/blob/4454204979f67ae15ffbca7140fdccc183adf4e8/mobile_insight/analyzer/msg_logger.py#L99):
```python
    self.__msg_log.append(msg)
```

I think this should fix your problem.

**Comment by ywk0bwl** [comment]
Hi dboyan,

Thanks, this worked for me!
